site_url: https://melas-rezepte.vercel.app

locale: "de"
backend:
  name: github
  repo: janheini/melas-rezepte
  branch: main
  base_url: https://melas-rezepte.vercel.app

# npx netlify-cms-proxy-server
local_backend: true

publish_mode: editorial_workflow
media_folder: "src/assets/"
public_folder: "../../assets/"

collections:

  - name: rezept
    label: Rezepte
    label_singular: Rezept
    folder: src/content/rezepte
    create: true
    summary: "{{title}}"
    # sortable_fields: [title]
    editor: { preview: false }
    fields:

      - label: "Titel"
        name: "title"
        widget: "string" 

      - label: "Titelbild"
        name: "image"
        widget: "image"
        required: false

      - label: "Tags"
        name: "tags"
        widget: "select" 
        multiple: true
        options:
          - "Vegetarisch"
          - "Fleisch"
          - "Huhn"
          - "Fisch"
          - "Garnelen"
          - "Reis"
          - "Nudeln"
          - "Kartoffeln"
          - "Gnocchi"

      - label: "Zeit"
        name: "time"
        widget: "select" 
        options:
          - "Schnell"
          - "Mittel"
          - "Lange"

      - label: Zutaten
        name: "ingredients"
        widget: "list"
        fields: 
          - { label: "", name: "ingredient", widget: "string" }

      - label: "Anleitung"
        name: "body"
        widget: "markdown" 
