name: convert rezepte to utf-8
on: push

jobs:
  convert:
    name: Convert ISO-8859-1 recipes to UTF-8
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |

          for file in src/content/rezepte/*.md; do 
            file "$file" | grep -q UTF-8 || iconv -f ISO-8859-1 -t UTF-8 "$file" -o "$file";
          done

          git config user.name "janheini"
          git config user.email "janheinemeyer99@gmail.com"
          git add .
          git commit -m "convert non-utf-8 files to utf-8" || true
          git push
